name: Generate Download

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ZIP Files 
        uses: papeloto/action-zip@v1
        with:
          files: assets pack.png pack.mcmeta LICENSE README.md
          dest: SMPPack.zip
          recursive: false
      - name: Commit & Push ZIP
        run: bash zip.sh